title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
github.is_user_page : false
google_analytics:
theme: jekyll-theme-minimal
