title: Li, Xingjian
logo: https://github.com/XJ-LI/XJ-LI.github.io/blob/main/P_20230823_152205.jpg
description: Updated 2023 summer.
show_downloads: false
github:
  is_user_page: false
google_analytics:
theme: jekyll-theme-minimal
